### ISSUE TITLE
Duplicate chunk label 'html'

### ISSUE THREAD

**Issue by WillemSleegers** [rethinkpriorities/methodology-statistics-design#1]
Hi,

I pulled the repository to my laptop but when I try to build it, it gives me the error message `Duplicate chunk label 'html'`. The issue is in `Index.Rmd`. 

I don't want to mess around too much yet and change things. My goal was to just download the rep and get it to work. I suppose it doesn't work out of the box just yet?

**Comment by daaronr** [comment]
Tip on duplicate chunks (I think I had this in the tips somewhere, but its
a lot to wade through).

Build with:

{
  options(knitr.duplicate.label = "allow")
  rmarkdown::render_site(output_format = 'bookdown::gitbook', encoding =
'UTF-8')
}

That should fix it, I think

**Comment by WillemSleegers** [comment]
That does fix it; but because it's apparently the only duplicate chunk label, I would fix it by not making it a duplicate one. ;)
